/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jaspe
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        tiktokSlider.setValue(0);
        instagramSlider.setValue(0);
        redditSlider.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        habitsTitle = new javax.swing.JLabel();
        tipsButton = new javax.swing.JToggleButton();
        tiktokSlider = new javax.swing.JSlider();
        instagramSlider = new javax.swing.JSlider();
        redditSlider = new javax.swing.JSlider();
        tiktokLabel = new javax.swing.JLabel();
        instagramLabel = new javax.swing.JLabel();
        redditLabel = new javax.swing.JLabel();
        tiktokHours = new javax.swing.JTextField();
        instagramHours = new javax.swing.JTextField();
        redditHours = new javax.swing.JTextField();
        stalkabilityTitle = new javax.swing.JLabel();
        check1 = new javax.swing.JCheckBox();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check4 = new javax.swing.JCheckBox();
        check5 = new javax.swing.JCheckBox();
        calculateButon = new javax.swing.JToggleButton();
        resultLabel = new javax.swing.JLabel();
        tipsLabel = new javax.swing.JLabel();
        stalkabilityTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stalkRisk = new javax.swing.JLabel();
        dailyHours = new javax.swing.JLabel();
        daysWasted = new javax.swing.JLabel();
        stalkRisk2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("Digital Footprint Tracker");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 6, -1, -1));

        habitsTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        habitsTitle.setText("Your Habits: (Time -- Posts per week)");
        getContentPane().add(habitsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 52, -1, -1));

        tipsButton.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tipsButton.setText("Tips");
        getContentPane().add(tipsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        tiktokSlider.setMaximum(24);
        getContentPane().add(tiktokSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 83, 90, -1));

        instagramSlider.setMaximum(24);
        getContentPane().add(instagramSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 120, 90, -1));

        redditSlider.setMaximum(24);
        getContentPane().add(redditSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 160, 90, -1));

        tiktokLabel.setText("Tiktok:");
        getContentPane().add(tiktokLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 84, 37, -1));

        instagramLabel.setText("Instagram:");
        getContentPane().add(instagramLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 121, -1, -1));

        redditLabel.setText("Reddit:");
        getContentPane().add(redditLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 161, -1, -1));

        tiktokHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiktokHoursActionPerformed(evt);
            }
        });
        getContentPane().add(tiktokHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 81, 71, -1));

        instagramHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instagramHoursActionPerformed(evt);
            }
        });
        getContentPane().add(instagramHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 118, 71, -1));

        redditHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redditHoursActionPerformed(evt);
            }
        });
        getContentPane().add(redditHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 158, 71, -1));

        stalkabilityTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stalkabilityTitle.setText("Stalkability Risk");
        getContentPane().add(stalkabilityTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 214, -1, -1));

        check1.setText("Public Profile");
        getContentPane().add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 246, -1, -1));

        check2.setText("Real Name in User");
        getContentPane().add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 272, -1, -1));

        check3.setText("Posts with school/face");
        getContentPane().add(check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 298, -1, -1));

        check4.setText("Posts about daily routine");
        getContentPane().add(check4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 324, -1, -1));

        check5.setText("Location Sharing");
        check5.setToolTipText("");
        getContentPane().add(check5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 346, -1, -1));

        calculateButon.setText("Calculate Digital Footprint");
        getContentPane().add(calculateButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 433, -1, -1));

        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 462, 428, 2));

        tipsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tipsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 81, 143, 122));

        stalkabilityTitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stalkabilityTitle1.setText("Lifetime Stats");
        getContentPane().add(stalkabilityTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Daily Hours:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Stalkability Risk:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Days Wasted/Year:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        stalkRisk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stalkRisk.setForeground(new java.awt.Color(0, 102, 51));
        stalkRisk.setText("NONE");
        getContentPane().add(stalkRisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        dailyHours.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dailyHours.setText("0 hours");
        getContentPane().add(dailyHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 20));

        daysWasted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        daysWasted.setText("0 days");
        getContentPane().add(daysWasted, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        stalkRisk2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stalkRisk2.setText("0%");
        getContentPane().add(stalkRisk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiktokHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiktokHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiktokHoursActionPerformed

    private void instagramHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instagramHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instagramHoursActionPerformed

    private void redditHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redditHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redditHoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton calculateButon;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JCheckBox check5;
    private javax.swing.JLabel dailyHours;
    private javax.swing.JLabel daysWasted;
    private javax.swing.JLabel habitsTitle;
    private javax.swing.JTextField instagramHours;
    private javax.swing.JLabel instagramLabel;
    private javax.swing.JSlider instagramSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField redditHours;
    private javax.swing.JLabel redditLabel;
    private javax.swing.JSlider redditSlider;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel stalkRisk;
    private javax.swing.JLabel stalkRisk2;
    private javax.swing.JLabel stalkabilityTitle;
    private javax.swing.JLabel stalkabilityTitle1;
    private javax.swing.JTextField tiktokHours;
    private javax.swing.JLabel tiktokLabel;
    private javax.swing.JSlider tiktokSlider;
    private javax.swing.JToggleButton tipsButton;
    private javax.swing.JLabel tipsLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
