/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jaspe & wilso
 */
public class NewJFrame extends javax.swing.JFrame {
DataManager dataManager = new DataManager();
    /**
     * Creates new form NewJFrame
     */
    public static int score = 0;
    public NewJFrame() {
        initComponents();
        tiktokSlider.setValue(0);
        instagramSlider.setValue(0);
        redditSlider.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        habitsTitle = new javax.swing.JLabel();
        tiktokSlider = new javax.swing.JSlider();
        instagramSlider = new javax.swing.JSlider();
        redditSlider = new javax.swing.JSlider();
        tiktokLabel = new javax.swing.JLabel();
        instagramLabel = new javax.swing.JLabel();
        instaBoxLabel = new javax.swing.JLabel();
        tiktokReels = new javax.swing.JTextField();
        instagramReels = new javax.swing.JTextField();
        stalkabilityTitle = new javax.swing.JLabel();
        check1 = new javax.swing.JCheckBox();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check4 = new javax.swing.JCheckBox();
        check5 = new javax.swing.JCheckBox();
        calculateButon = new javax.swing.JToggleButton();
        resultLabel = new javax.swing.JLabel();
        tipsLabel = new javax.swing.JLabel();
        stalkabilityTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stalkRisk = new javax.swing.JLabel();
        dailyHours = new javax.swing.JLabel();
        daysWasted = new javax.swing.JLabel();
        stalkRisk2 = new javax.swing.JLabel();
        instagramPosts = new javax.swing.JTextField();
        redditPosts = new javax.swing.JTextField();
        habitsTitle1 = new javax.swing.JLabel();
        tipsButton = new javax.swing.JToggleButton();
        redditLabel1 = new javax.swing.JLabel();
        redditBoxLabel = new javax.swing.JLabel();
        tiktokBoxLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("Digital Footprint Tracker");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 6, -1, -1));

        habitsTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        habitsTitle.setText("Posts/Day - Reels/Day");
        getContentPane().add(habitsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 20));

        tiktokSlider.setMaximum(24);
        tiktokSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tiktokSliderStateChanged(evt);
            }
        });
        getContentPane().add(tiktokSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 83, 90, -1));

        instagramSlider.setMaximum(24);
        instagramSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                instagramSliderStateChanged(evt);
            }
        });
        getContentPane().add(instagramSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 120, 90, -1));

        redditSlider.setMaximum(24);
        redditSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redditSliderStateChanged(evt);
            }
        });
        getContentPane().add(redditSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 160, 90, -1));

        tiktokLabel.setText("Tiktok:");
        getContentPane().add(tiktokLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 84, 37, -1));

        instagramLabel.setText("Instagram:");
        getContentPane().add(instagramLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 121, -1, -1));

        instaBoxLabel.setText("0 hours spent total");
        getContentPane().add(instaBoxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        tiktokReels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiktokReelsActionPerformed(evt);
            }
        });
        getContentPane().add(tiktokReels, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 40, -1));

        instagramReels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instagramReelsActionPerformed(evt);
            }
        });
        getContentPane().add(instagramReels, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 40, -1));

        stalkabilityTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stalkabilityTitle.setText("Stalkability Risk");
        getContentPane().add(stalkabilityTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 214, -1, -1));

        check1.setText("Public Profile");
        getContentPane().add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 246, -1, -1));

        check2.setText("Real Name in User");
        getContentPane().add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 272, -1, -1));

        check3.setText("Posts with school/face");
        getContentPane().add(check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 298, -1, -1));

        check4.setText("Posts about daily routine");
        getContentPane().add(check4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 324, -1, -1));

        check5.setText("Location Sharing");
        check5.setToolTipText("");
        getContentPane().add(check5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 346, -1, -1));

        calculateButon.setText("Calculate Digital Footprint");
        calculateButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 433, -1, -1));

        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 462, 428, 80));

        tipsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tipsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 143, 122));

        stalkabilityTitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stalkabilityTitle1.setText("Lifetime Stats");
        getContentPane().add(stalkabilityTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Daily Hours:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Stalkability Risk:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Days Wasted/Year:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        stalkRisk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stalkRisk.setForeground(new java.awt.Color(0, 102, 51));
        stalkRisk.setText("NONE");
        getContentPane().add(stalkRisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        dailyHours.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dailyHours.setText("0 hours");
        getContentPane().add(dailyHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 20));

        daysWasted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        daysWasted.setText("0 days");
        getContentPane().add(daysWasted, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        stalkRisk2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stalkRisk2.setText("0%");
        getContentPane().add(stalkRisk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));
        getContentPane().add(instagramPosts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 40, -1));
        getContentPane().add(redditPosts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 40, -1));

        habitsTitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        habitsTitle1.setText("Your Habits (Time):");
        getContentPane().add(habitsTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        tipsButton.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tipsButton.setText("Tips");
        tipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tipsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        redditLabel1.setText("Reddit:");
        getContentPane().add(redditLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 161, -1, -1));

        redditBoxLabel.setText("0 hours spent total");
        getContentPane().add(redditBoxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 20));

        tiktokBoxLabel.setText("0 hours spent total");
        getContentPane().add(tiktokBoxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiktokReelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiktokReelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiktokReelsActionPerformed

    private void instagramReelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instagramReelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instagramReelsActionPerformed

    private void redditPostHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redditPostHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redditPostHoursActionPerformed

    private void calculateButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButonActionPerformed
        try {
            // Reset variables
            Socials.resetTotals(); 
            // ensure score is 0
            NewJFrame.score = 0; 

            // Get time from sliders
            int tiktokHours = tiktokSlider.getValue();
            int instaHours = instagramSlider.getValue();
            int redditHours = redditSlider.getValue();

            // Get count from text boes
            int tr = tiktokReels.getText().isEmpty() ? 0 : Integer.parseInt(tiktokReels.getText());
            int ir = instagramReels.getText().isEmpty() ? 0 : Integer.parseInt(instagramReels.getText());
            int ip = instagramPosts.getText().isEmpty() ? 0 : Integer.parseInt(instagramPosts.getText());
            int rp = redditPosts.getText().isEmpty() ? 0 : Integer.parseInt(redditPosts.getText());
            
            // Calculate Checkbox Score
            score += (check1.isSelected()) ? 15 : 0; 
            score += (check2.isSelected()) ? 15 : 0;
            score += (check3.isSelected()) ? 15 : 0;
            score += (check4.isSelected()) ? 15 : 0;
            score += (check5.isSelected()) ? 15 : 0;

            // Create Objects
            Socials[] socials = new Socials[3];
            socials[0] = new TikTok(tiktokHours, tr);
            socials[1] = new Instagram(instaHours, ir, ip);
            socials[2] = new Reddit(redditHours, rp);

            // Calculate Risk
            double finalRisk = 0;
            int totalHours = tiktokHours + instaHours + redditHours;
            
            // Cap visual hours at 24
            if(totalHours > 24) totalHours = 24; 
            
            // Loop through objects to sum up risk
            for (Socials s : socials) {
                finalRisk += s.calculateStalkability();
            }
            
            if (finalRisk > 100) finalRisk = 100;

            // Update UI Labels
            dailyHours.setText(totalHours + " hours spent total");
            
            // Calculate Days Wasted
            double days = (totalHours * 365) / 24.0;
            daysWasted.setText(String.format("%.1f", days) + " days");
            
            stalkRisk2.setText(String.format("%.1f", finalRisk) + "%");
            
            // Risk Status Color
            if (finalRisk < 30) {
                stalkRisk.setText("LOW");
                stalkRisk.setForeground(java.awt.Color.GREEN);
            } else if (finalRisk < 70) {
                stalkRisk.setText("MEDIUM");
                stalkRisk.setForeground(java.awt.Color.ORANGE);
            } else {
                stalkRisk.setText("CRITICAL");
                stalkRisk.setForeground(java.awt.Color.RED);
            }

            // Save to File
            dataManager.saveResultLog(totalHours, finalRisk);
            
            resultLabel.setText("Calculation Complete. Data saved.");

        } catch (NumberFormatException e) {
            resultLabel.setText("Error: Please enter numbers only.");
        } catch (Exception e) {
            resultLabel.setText("An error occurred: " + e.getMessage());
        }
    }//GEN-LAST:event_calculateButonActionPerformed

    private void tiktokSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tiktokSliderStateChanged
        // Updates boxes to show hours
        tiktokBoxLabel.setText("TikTok: " + tiktokSlider.getValue() + " hrs spent total");
    }//GEN-LAST:event_tiktokSliderStateChanged

    private void instagramSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_instagramSliderStateChanged
        instaBoxLabel.setText("Instagram: " + instagramSlider.getValue() + " hrs spent total");
    }//GEN-LAST:event_instagramSliderStateChanged

    private void redditSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redditSliderStateChanged
        redditBoxLabel.setText("Reddit: " + redditSlider.getValue() + " hrs spent total");
    }//GEN-LAST:event_redditSliderStateChanged

    private void tipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipsButtonActionPerformed
        //Get random tip
        String randomTip = dataManager.getRandomTip();
        
        //Update the Label
        //using HTML tags to make the text wrap automatically if it's too long
        tipsLabel.setText("<html><center>" + randomTip + "</center></html>");
    }//GEN-LAST:event_tipsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton calculateButon;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JCheckBox check5;
    private javax.swing.JLabel dailyHours;
    private javax.swing.JLabel daysWasted;
    private javax.swing.JLabel habitsTitle;
    private javax.swing.JLabel habitsTitle1;
    private javax.swing.JLabel instaBoxLabel;
    private javax.swing.JLabel instagramLabel;
    private javax.swing.JTextField instagramPosts;
    private javax.swing.JTextField instagramReels;
    private javax.swing.JSlider instagramSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel redditBoxLabel;
    private javax.swing.JLabel redditLabel1;
    private javax.swing.JTextField redditPosts;
    private javax.swing.JSlider redditSlider;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel stalkRisk;
    private javax.swing.JLabel stalkRisk2;
    private javax.swing.JLabel stalkabilityTitle;
    private javax.swing.JLabel stalkabilityTitle1;
    private javax.swing.JLabel tiktokBoxLabel;
    private javax.swing.JLabel tiktokLabel;
    private javax.swing.JTextField tiktokReels;
    private javax.swing.JSlider tiktokSlider;
    private javax.swing.JToggleButton tipsButton;
    private javax.swing.JLabel tipsLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
